source 'https://github.com/CocoaPods/Specs.git'
# Uncomment the next line to define a global platform for your project
platform :ios, '17.0'

target 'coinTracker' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for coinTracker
# Add the Firebase pod for Google Analytics
pod 'FirebaseAnalytics'

# For Analytics without IDFA collection capability, use this pod instead
# pod ‘Firebase/AnalyticsWithoutAdIdSupport’

# Add the pods for any other Firebase products you want to use in your app
# For example, to use Firebase Authentication and Cloud Firestore
pod 'FirebaseAuth'
pod 'FirebaseFirestore'
pod 'Firebase/Database'
pod 'Kingfisher', '~> 7.0'
pod 'DGCharts'
  target 'coinTrackerTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'coinTrackerUITests' do
    # Pods for testing
  end

end
